import type { Fiesta } from "../../hooks/useFiestas";

/** Calendario de respaldo cuando la API no devuelve fiestas. */
export const FALLBACK_FIESTAS: Fiesta[] = [
  {
    id: -1,
    municipio_nombre: "Nuquí",
    corregimiento: null,
    nombre_fiesta: "Fiesta del Tamborito",
    mes: 1,
    fechas_texto: "5 — 7 Ene",
    fecha_inicio_dia: 5,
    fecha_fin_dia: 7,
    es_principal: true,
  },
  {
    id: -2,
    municipio_nombre: "Quibdó",
    corregimiento: null,
    nombre_fiesta: "Carnaval",
    mes: 2,
    fechas_texto: "Feb — variable",
    fecha_inicio_dia: 1,
    fecha_fin_dia: 28,
    es_principal: false,
  },
  {
    id: -3,
    municipio_nombre: "Istmina",
    corregimiento: null,
    nombre_fiesta: "Semana Santa",
    mes: 3,
    fechas_texto: "Mar/Abr — variable",
    fecha_inicio_dia: 1,
    fecha_fin_dia: 31,
    es_principal: false,
  },
  {
    id: -4,
    municipio_nombre: "Unión Panamericana",
    corregimiento: null,
    nombre_fiesta: "Divino Ecce-Homo",
    mes: 4,
    fechas_texto: "24 Abr — 1 May",
    fecha_inicio_dia: 24,
    fecha_fin_dia: 1,
    es_principal: true,
  },
  {
    id: -5,
    municipio_nombre: "Quibdó",
    corregimiento: null,
    nombre_fiesta: "Fiestas de la Cruz",
    mes: 5,
    fechas_texto: "Mayo",
    fecha_inicio_dia: 1,
    fecha_fin_dia: 31,
    es_principal: false,
  },
  {
    id: -6,
    municipio_nombre: "Condoto",
    corregimiento: null,
    nombre_fiesta: "Corpus Christi",
    mes: 6,
    fechas_texto: "Jun — variable",
    fecha_inicio_dia: 1,
    fecha_fin_dia: 30,
    es_principal: false,
  },
  {
    id: -7,
    municipio_nombre: "Bajo Baudó",
    corregimiento: "Pizarro",
    nombre_fiesta: "India Sivirá",
    mes: 7,
    fechas_texto: "16 Jul",
    fecha_inicio_dia: 16,
    fecha_fin_dia: 16,
    es_principal: true,
  },
  {
    id: -8,
    municipio_nombre: "San José del Palmar",
    corregimiento: null,
    nombre_fiesta: "Fiestas del Chontaduro",
    mes: 8,
    fechas_texto: "8 — 15 Ago",
    fecha_inicio_dia: 8,
    fecha_fin_dia: 15,
    es_principal: true,
  },
  {
    id: -9,
    municipio_nombre: "Bahía Solano",
    corregimiento: null,
    nombre_fiesta: "Festival de la Bahía",
    mes: 8,
    fechas_texto: "Agosto",
    fecha_inicio_dia: 1,
    fecha_fin_dia: 31,
    es_principal: true,
  },
  {
    id: -10,
    municipio_nombre: "Tadó",
    corregimiento: null,
    nombre_fiesta: "Virgen de la Pobreza",
    mes: 8,
    fechas_texto: "30 Ago — 8 Sept",
    fecha_inicio_dia: 30,
    fecha_fin_dia: 8,
    es_principal: true,
  },
  {
    id: -11,
    municipio_nombre: "Quibdó",
    corregimiento: null,
    nombre_fiesta: "San Francisco de Asís — San Pacho",
    mes: 9,
    fechas_texto: "20 Sept — 5 Oct",
    fecha_inicio_dia: 20,
    fecha_fin_dia: 5,
    es_principal: true,
  },
  {
    id: -12,
    municipio_nombre: "Quibdó",
    corregimiento: null,
    nombre_fiesta: "Fiestas de octubre",
    mes: 10,
    fechas_texto: "Octubre",
    fecha_inicio_dia: 1,
    fecha_fin_dia: 31,
    es_principal: false,
  },
  {
    id: -13,
    municipio_nombre: "Lloró",
    corregimiento: null,
    nombre_fiesta: "Conmemoraciones locales",
    mes: 11,
    fechas_texto: "Noviembre",
    fecha_inicio_dia: 1,
    fecha_fin_dia: 30,
    es_principal: false,
  },
  {
    id: -14,
    municipio_nombre: "Unguía",
    corregimiento: null,
    nombre_fiesta: "Festival del Bocachico",
    mes: 12,
    fechas_texto: "Anual",
    fecha_inicio_dia: 1,
    fecha_fin_dia: 31,
    es_principal: true,
  },
];
